[tool.poetry]
name = "unesco_data_collection"
version = "0.2.0"
description = "Curation of UNESCO documents for the INIDUN project."
authors = ["aibakeneko <aibakeneko at gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
argh = "^0.26.2"
bs4 = "^0.0.1"
Jinja2 = "^2.11.3"
loguru = "^0.5.3"
mypy = "^0.812"
pandas = "^1.2.3"
pdf2image = "^1.14.0"
pytesseract = "^0.3.7"
python-pdfbox = "^0.1.8"
requests = "^2.25.1"
tqdm = "^4.59.0"
untangle = "^1.1.1"
pdfplumber = "^0.5.27"
nltk = "^3.6.2"
fuzzysearch = "^0.7.3"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
flake8-black = "^0.2.1"
flake8-pytest-style = "^1.4.1"
flake8-quotes = "^3.2.0"
httpretty = "^1.0.5"
ipykernel = "^5.5.0"
isort = "^5.8.0"
mypy = "^0.812"
pylint = "^2.7.2"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
rope = "^0.18.0"
pyinstrument = "^3.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ["py38"]
exclude = '''
(
  \.git
  | \.pypy_cache
  | \.pytest_cache
  | \.mypy_cache
  | deprecated
)
'''

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.isort]
profile = "black"
line_length = 120
py_version = "auto"
float_to_top = true
src_paths = [ "courier", "legal_instruments", "tests", "tmp" ]

[tool.pytest.ini_options]
log_cli = "False"
testpaths = [
    "tests",
]
python_files = "*_test.py"
python_functions = "test_*"


[tool.coverage.run]
branch = true
omit = [
    "**/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]
show_missing = true
sort = "Name"